[0m09:40:37.568078 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000230FFCB2900>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002308315CD40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002308282EB40>]}


============================== 09:40:37.581121 | 22d546de-41c6-4388-9e8f-5d86127315e0 ==============================
[0m09:40:37.581121 [info ] [MainThread]: Running with dbt=1.9.2
[0m09:40:37.583089 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\user\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m09:40:48.893411 [debug] [MainThread]: Starter project path: E:\DBT\venv\Lib\site-packages\dbt\include\starter_project
[0m09:40:48.930461 [info ] [MainThread]: 
Your new dbt project "dlyticadbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:40:48.934506 [info ] [MainThread]: Setting up your profile.
[0m09:41:52.426833 [info ] [MainThread]: Profile dlyticadbt written to C:\Users\user\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m09:41:52.430802 [debug] [MainThread]: Command `dbt init` succeeded at 09:41:52.430802 after 75.39 seconds
[0m09:41:52.431793 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023082AB57F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023082B549E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023082EA48C0>]}
[0m09:41:52.432792 [debug] [MainThread]: Flushing usage events
[0m09:41:55.478940 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:05:16.809940 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002734CFD2960>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002734F2CFE30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002734F2CFF50>]}


============================== 00:05:16.819943 | e4a5a496-59e3-4b11-ba1a-2f6b067b8c7e ==============================
[0m00:05:16.819943 [info ] [MainThread]: Running with dbt=1.9.2
[0m00:05:16.821913 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\user\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run -m tran_convert_to_date', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:05:16.823969 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path E:\DBT\DBT\HomeWorkDBT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:05:16.824971 [debug] [MainThread]: Command `dbt run` failed at 00:05:16.824971 after 0.27 seconds
[0m00:05:16.825912 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002734DA935F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002734CFD2960>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002734F266A20>]}
[0m00:05:16.826955 [debug] [MainThread]: Flushing usage events
[0m00:05:18.092153 [debug] [MainThread]: An error was encountered while trying to flush usage events
